set(CMAKE_SYSTEM_NAME Windows)

set(MSVC_BIN_DIR $ENV{MSVC_BIN_DIR})
set(CMAKE_C_COMPILER ${MSVC_BIN_DIR}/cl)
set(CMAKE_CXX_COMPILER ${MSVC_BIN_DIR}/cl)
set(CMAKE_RC_COMPILER ${MSVC_BIN_DIR}/rc)

# FIX LINK : fatal error LNK1158: cannot run 'rc.exe'
set(CMAKE_EXE_LINKER_FLAGS /MANIFEST:NO)
set(CMAKE_SHARED_LINKER_FLAGS /MANIFEST:NO)

set(CMAKE_PROJECT_INCLUDE ${CMAKE_CURRENT_LIST_DIR}/qt-wine.cmake)

